# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/primes/primes/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/primes/primes

PRODUCT_COPY_FILES += \
    vendor/primes/primes/proprietary/system_ext/fonts/montserrat/Android.bp:$(TARGET_COPY_OUT_SYSTEM_EXT)/fonts/montserrat/Android.bp \
    vendor/primes/primes/proprietary/system_ext/fonts/montserrat/METADATA:$(TARGET_COPY_OUT_SYSTEM_EXT)/fonts/montserrat/METADATA \
    vendor/primes/primes/proprietary/system_ext/fonts/montserrat/MODULE_LICENSE_OFL:$(TARGET_COPY_OUT_SYSTEM_EXT)/fonts/montserrat/MODULE_LICENSE_OFL \
    vendor/primes/primes/proprietary/system_ext/fonts/montserrat/Montserrat.ttf:$(TARGET_COPY_OUT_SYSTEM_EXT)/fonts/montserrat/Montserrat.ttf \
    vendor/primes/primes/proprietary/system_ext/fonts/montserrat/NOTICE:$(TARGET_COPY_OUT_SYSTEM_EXT)/fonts/montserrat/NOTICE \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/7z:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/7z \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/7za:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/7za \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/7zz:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/7zz \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/aapt:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/aapt \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/aapt2:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/aapt2 \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/bash:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/bash \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/curl:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/curl \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/curl-config:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/curl-config \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/dialog:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/dialog \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/diff3:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/diff3 \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/eza:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/eza \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/fdroidcl:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/fdroidcl \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/file:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/file \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gh:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gh \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/glab:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/glab \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpg:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpg \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpg-agent:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpg-agent \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpg-card:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpg-card \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpg-connect-agent:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpg-connect-agent \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpg-error:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpg-error \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpg-error-config:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpg-error-config \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpg-wks-client:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpg-wks-client \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgconf:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgconf \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgme-config:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgme-config \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgme-json:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgme-json \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgme-tool:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgme-tool \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgparsemail:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgparsemail \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgrt-config:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgrt-config \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgscm:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgscm \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgsm:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgsm \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgsplit:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgsplit \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgtar:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgtar \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/gpgv:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/gpgv \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/hexdump:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/hexdump \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/hexedit:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/hexedit \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/jq:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/jq \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/megatools:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/megatools \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/micro:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/micro \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/nmap:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/nmap \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/pkill:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/pkill \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/repack_bootimg:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/repack_bootimg \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/scp:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/scp \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/ssh:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/ssh \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/ssh-add:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/ssh-add \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/ssh-agent:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/ssh-agent \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/ssh-copy-id:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/ssh-copy-id \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/ssh-keygen:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/ssh-keygen \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/ssh-keyscan:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/ssh-keyscan \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/ssha:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/ssha \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/sshd:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/sshd \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/tmux:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/tmux \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/tree:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/tree \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/tsu:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/tsu \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/unpack_bootimg:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/unpack_bootimg \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/wcalc:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/wcalc \
    vendor/primes/primes/proprietary/system_ext/primesenv/xbin/zsh:$(TARGET_COPY_OUT_SYSTEM_EXT)/primesenv/xbin/zsh \
    vendor/primes/primes/proprietary/vendor/lib/libv4a_re.so:$(TARGET_COPY_OUT_VENDOR)/lib/libv4a_re.so \
    vendor/primes/primes/proprietary/vendor/lib64/libv4a_re.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libv4a_re.so

PRODUCT_PACKAGES += \
    adaway \
    term \
    v4a_re
