# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/salami/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/primes/primes

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/permissions/privapp-permissions-termone.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-termone.xml \
	$(LOCAL_PATH)/configs/audio/audio_effects.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/audio_effects.xml

$(call inherit-product, $(LOCAL_PATH)/primes-vendor.mk)
